sudo: required

services:
  - docker

script:
  - docker build --tag "${DOCKER_ADDRESS}/${REGISTRY_USER}/${SERVER_IMAGE_NAME}" server/.


before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "${DOCKER_ADDRESS}/${REGISTRY_USER}/${SERVER_IMAGE_NAME}""

notifications:
  slack: lucid-visions:WVPXvEOYvigHF2gpVHAGl3Yh