language: node_js
node_js:
  - "node"
cache: 
  yarn: true
  directories:
    - "$HOME/google-cloud-sdk/"
services:
  - docker
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash  > /dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
deploy:
  - provider: script
    script: chmod +x script/docker-build-push.sh && script/docker-build-push.sh
    skip_cleanup: true
    on:
      branch: fix-travis-build
notifications:
  slack: lucid-visions:WVPXvEOYvigHF2gpVHAGl3Yh
