steps:
# pintro-server image (build and push latest and $COMMIT_SHA)
- id: 'pintro-server:latest'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/pintro-server', 'server' ]

- id: 'pintro-server:$COMMIT_SHA'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'eu.gcr.io/$PROJECT_ID/pintro-server', 'eu.gcr.io/$PROJECT_ID/pintro-server:$COMMIT_SHA' ]
  wait_for: ['pintro-server:latest']

# mongo-seed image (build and push latest and $COMMIT_SHA)
- id: 'mongo-seed:latest'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/mongo-seed', 'docker/mongo-seed' ]

- id: 'mongo-seed:$COMMIT_SHA'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'eu.gcr.io/$PROJECT_ID/mongo-seed', 'eu.gcr.io/$PROJECT_ID/mongo-seed:$COMMIT_SHA' ]

images:
- 'eu.gcr.io/$PROJECT_ID/mongo-seed'
- 'eu.gcr.io/$PROJECT_ID/pintro-server'