version: '3.1'

services:

  mongo:
    image: mongo:4.2.3
    restart: always
    container_name: mongo
    ports:
      - 27017-27019:27017-27019

  mongo-seed:
    image: eu.gcr.io/onyx-seeker-278919/mongo-seed
    container_name: mongo-seed
    links:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  pintro-server:
    image: eu.gcr.io/onyx-seeker-278919/pintro-server
    container_name: pintro-server
    volumes:
      - ./server:/app
    ports:
      - 443:443
      - 3000:3000
    environment:
      PORT_HTTPS: 443
      PORT_HTTP: 3000
    depends_on:
      - mongo
