version: '3.1'

services:

  mongodb:
    image: mongo:4.2.3
    restart: always
    container_name: mongo
    ports:
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-seed:
    image: eu.gcr.io/pintro-279114/mongo-seed:b532233f211faa134a366120b675dd248b884624
    container_name: mongo-seed
    links:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  pintro-server:
    image: eu.gcr.io/pintro-279114/pintro-server:b532233f211faa134a366120b675dd248b884624
    container_name: pintro-server
    volumes:
      - ./server:/app
    ports:
      - 443:443
      - 3000:3000
    environment:
      PORT_HTTPS: 443
      PORT_HTTP: 3000
      MONGO_HOST: mongodb
    depends_on:
      - mongodb
